### ISSUE TITLE
Herramientas sistema

### ISSUE THREAD

**Issue by dynobro** [araucanosland/Galvarino#12]
Estas herramientas son necesarias para administrar la aplicación
- [x] Mantenedor Usuarios
- [x] Mantenedor Roles (administrador sistema)
- [x] Visor de Cargas Iniciales Diarias
- [x] Mantenedor Workflow
- [x] Configuración de Documentos (**requiere migración**)
- [x] Mantenedor Notarías
- [ ] Mantenedor Oficinas
- [ ] Mantenedor Comunas
- [x] Mantenedor Organización
- [x] Visor Gráfico de Workflows
- [ ] Reasigna Workflows
- [x] Tacking de solicitudes

**Comment by capradenas** [comment]
Visor de cargas iniciales diarias: Este reporte me muestra los datos cargado en carga inicial por día
