### ISSUE TITLE
Etapa solucion documentos o expediente faltante

### ISSUE THREAD

**Issue by Charlie8810** [araucanosland/Galvarino#2]
En esta etapa se debe ver los documentos que estan faltantes, aqui no se envia ningun documento a la oficina solo se le notifica para que haga llegar el documento (s) faltante (s) en la siguiente valija.

Al marcar como resuelto el expediente este quedará para despacho hacia la oficina de partes y se marcará de forma especial.

Tareas:
- [x] Listado de expedientes con documentacion faltante, esta debe mostrar los documentos faltantes
- [x] Avanzar etapa a destino correspondiente

**Comment by capradenas** [comment]
Revisar bien.
