### ISSUE TITLE
Set Complementario 

### ISSUE THREAD

**Issue by capradenas** [araucanosland/Galvarino#21]
CP: Se debe desarrollar un nuevo mapa el cual pueda soportar el envio de documentos entre oficinas

MC: Generar nuevo flujo para realizar despacho de aquellos documentos que son generados al momento de la formalización del crédito “Pagaré” (Set complementario), hoy en día esta acción se hace por NI Manual, pero no existe un control ni trazabilidad. 

**Tareas**
 - [ ] Identificar Etapas

**Comment by victorarroyonavarro** [comment]
Set Complementarios [4 dic]
