### ISSUE TITLE
Nominas Especiales (Corregir)

### ISSUE THREAD

**Issue by capradenas** [araucanosland/Galvarino#22]
Las nominas especiales no estan funcionando

- [x] Crear Etapa MCC
- [x] Traspaso Stock Pendientes Sucursales a Etapa MCC
- [x] Cruce Stock con base Hans
- [x] Fix proceso NOminas Especiales

**Comment by victorarroyonavarro** [comment]
[Casos de pruebas Nominas especiales.pdf](https://github.com/araucanosland/Galvarino/files/3560068/Casos.de.pruebas.Nominas.especiales.pdf)

@mvegaalarcon adjunto casos de pruebas para nóminas especiales tanto para regiones  como para RM.
