### ISSUE TITLE
Reasignación Oficina Expedientes Legales

### ISSUE THREAD

**Issue by mvegaalarcon** [araucanosland/Galvarino#30]
Reasignación de Expediente legales, esta función también ha presentado inconvenientes, dado que no se traspasa el registro a la sucursal seleccionada.

- [x] Revisar Proceso
- [ ] Corrección si corresponde

**Comment by victorarroyonavarro** [comment]
se realizaron cambios para reasignación de oficinas legales , se modificó código agregando validación RM y Regiones.
