### ISSUE TITLE
Cambio Oficina Set Comercial

### ISSUE THREAD

**Issue by mvegaalarcon** [araucanosland/Galvarino#32]
7.	Habilitar la opción de cambiar registros “Comercial” tal como se hace hoy con los registro legales.

**Comment by victorarroyonavarro** [comment]
Se realizaron mejoras para reasignación de oficina set comercial , utilizando la misma pantalla definiendo combos para cambio de oficina comercial y legal y modifcando el Backend según opción seleccionado en combo.

**Comment by victorarroyonavarro** [comment]
Se  sube a producción
