### ISSUE TITLE
Nómina Especiales sprint2 [29oct]

### ISSUE THREAD

**Issue by mvegaalarcon** [araucanosland/Galvarino#42]
sprint1 
 - [x] en nomina añadir marca  OK 11/10

sprint2
 - [ ] en Analizar Documentos de Mesa de Control, añadir las opciones de Nulos y Acuerdo Pago Total
  - [ ] al procesar debe enviar estos casos a nuevo estado " Despacho Custodia NE" (crear estado)

**Comment by victorarroyonavarro** [comment]
En revisión, hay que definir los estados de las nóminas especiales , al momento de anularlas o pago total, hay que definirlo con Mauricio.
